# Usage: Follow the steps in the README file in the directory containing this file
version: "3"
services:
    workspace:
        image: synthillect/opencog-minerl
        user: opencog
        ports:
            - "8888:8888" # Jupyter
            - "5901:5901" # VNC
            - "6901:6901" # noVNC
        volumes:
            - ..:/workspace:cached
            - ~/.ccache:/home/opencog/.ccache # for persisting ccache artifacts
        environment:
            - CCACHE_DIR=/home/opencog/.ccache
            - TZ=$TZ # set this to your timezone
        working_dir: /workspace
        command: jupyter lab --ip="0.0.0.0" --no-browser --ServerApp.token='' --ServerApp.password=''
