# Usage: Follow the steps in the README file in the directory containing this file
version: "3"
services:
    workspace:
        image: synthillect/opencog-minerl
        user: opencog
        ports:
            - "8888:8888" # Jupyter
            - "5901:5901" # VNC
            - "6901:6901" # noVNC, currently doesn't work
        volumes:
            - ..:/workspace:cached
            - ~/.ccache:/home/opencog/.ccache # for persisting ccache artifacts
        environment:
            - CCACHE_DIR=/home/opencog/.ccache
            - TZ=$TZ # set this to your timezone
        working_dir: /workspace
        # for some reason the entrypoint doesn't see the full PATH even though it's run by the appropriate user and even sources their .bashrc
        command: /home/opencog/.local/bin/jupyter lab --ip="0.0.0.0" --no-browser --ServerApp.token='' --ServerApp.password=''
